# -----------------------------------------------------------------------------
# Stage 1: Dependency Installation
# -----------------------------------------------------------------------------
# We use a specific version of Node.js on Alpine Linux for a small and secure base.
# Naming this stage "deps" allows us to reference it later.
FROM node:20-alpine AS deps

# Set the working directory inside the container.
WORKDIR /app

# Install pnpm, a fast and efficient package manager.
RUN npm install -g pnpm

# Copy the dependency manifest and lockfile.
# By copying only these files first, we leverage Docker's layer caching.
# This step will only re-run if these files change, making subsequent builds much faster.
COPY package.json pnpm-lock.yaml ./

# Use `pnpm fetch` to download all dependencies into a content-addressable store.
# This is more efficient for caching within Docker builds.
RUN pnpm fetch


# -----------------------------------------------------------------------------
# Stage 2: Application Builder
# -----------------------------------------------------------------------------
# This stage builds the actual Next.js application.
FROM node:20-alpine AS builder

WORKDIR /app

# Copy the pre-fetched dependencies from the "deps" stage.
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/pnpm-lock.yaml ./

# Copy the rest of your application's source code.
COPY . .

# Install dependencies using the lockfile. This will use the cached versions
# from the `pnpm fetch` command in the previous stage.
RUN npm install -g pnpm && pnpm install --frozen-lockfile

# Build the Next.js application for production.
# This step compiles your TypeScript, bundles your code, and optimizes assets.
RUN pnpm build


# -----------------------------------------------------------------------------
# Stage 3: Production Runner
# -----------------------------------------------------------------------------
# This is the final, lean image that will be deployed.
FROM node:20-alpine AS runner

WORKDIR /app

# Set the environment to "production" to enable Next.js optimizations.
ENV NODE_ENV production
# Disable Next.js telemetry.
ENV NEXT_TELEMETRY_DISABLED 1

# Create a dedicated, non-root user for running the application.
# This is a critical security best practice to limit potential container vulnerabilities.
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy the standalone output from the builder stage.
# The `standalone` output is a feature of Next.js that creates a minimal
# server with only the necessary files, resulting in a very small Docker image.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# Switch to the non-root user.
USER nextjs

# Expose the port the Next.js server will run on.
EXPOSE 3000

# Set the port environment variable.
ENV PORT 3000

# The command to start the application.
# It uses the standalone server file generated by the build process.
CMD ["node", "server.js"]